### ISSUE TITLE
We need a generic way to add (process) context to log messages

### ISSUE THREAD

**Issue by jasper-jager** [Amsterdam/GOB-Core#35]
At the moment log messages receive process_id, source, entity and data attributes. These are added in each component and passed along with the message metadata, so each component can use these attributes to log messages linked to the process_id.

For now this is something that is being handled in each component and would be nice if this would be centralised in gobcore. Maybe we can look at how other libraries handle automatic logging of context variables.

**Comment by jasper-jager** [comment]
We could look at how libraries like celery handle the current state and keep a reference to the current task/message and adds the task id and name to each log.

**Comment by Vegter** [comment]
Solved by initializing the logger with the message (header)
