### ISSUE TITLE
Unit test code coverage should be 100%

### ISSUE THREAD

**Issue by Vegter** [Amsterdam/GOB-Core#6]
The current code coverage is 70%.
Unit tests should be added to have GOB-Core be unit tested for 100% of its statements

**Comment by kerkuil** [comment]
Can we view these code-coverage statistics somewhere like on coveralls? And the unit-testing procedure before that like on travis?

**Comment by kerkuil** [comment]
Ok, thanks for the insight.

I assume you explicitly mentioned `statements` on purpose, right? To be sure it's not interpreted as 100% line coverage.

**Comment by Vegter** [comment]
Coverage on functions, branches, statements has for now been 'shortcutted' to statements.
