### ISSUE TITLE
Which branch/tag of GOB Core should be used?

### ISSUE THREAD

**Issue by Vegter** [Amsterdam/GOB-Core#7]
When GOB Core is used in the other GOB projects it is included by means of a reference
Example:
git://github.com/Amsterdam/GOB-Core.git#egg=gobcore
(Connects to the master branch of GOB Core)

It is possible to specify a reference to a specific commiy, branch or tag, example:
git://github.com/Amsterdam/GOB-Core.git@909301b10ec20f839d1db13fe2bf512ab56c3960#egg=gobcore

Local development might rely on changes that are not yet in the master branch of GOB Core.
While production needs to connect to the master GOB Core branch.

Propose for a solution that allows for both flexible local development and stable production.

**Comment by bvhme** [comment]
I would recommend either using a branching model such as Git-flow to make sure the `release` branch can always be used in production or using Tags to mark release versions. This can be done with Semantic Versioning or just rolling numbers. Development can then always use `develop` branch or tag while deployed versions can use the `release` branch or tags.
